=== Ajaykashela/Website17-7024/WebService/WebService/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="plant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="genus" >
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="species" type="xs:string"  minOccurs="0" default="spp."/>
        <xs:element name="cultivar" type="xs:string"  minOccurs="0"/>
        <xs:element name="common_name" type="xs:string"  minOccurs="0"/>
        <xs:element name="height" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:maxInclusive value="100"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="begin_bloom_date" type="xs:date"  minOccurs="0"/>
        <xs:element name="end_bloom_date" type="xs:date"  minOccurs="0"/>
        <xs:element name="edible" type="xs:boolean"  minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Ajaykashela/Website17-7024/WebService/WebService/plants.xml
<?xml version="1.0"?>
<plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plants.xsd">
  <genus>Cercis</genus>
  <species>canadensis</species>
  <cultivar>Ruby Falls</cultivar>
  <common_name>Ruby Falls Redbud</common_name>
  <height>100</height>
  <begin_bloom_date>2017-03-01</begin_bloom_date>
  <end_bloom_date>2017-03-15</end_bloom_date>
  <edible>true</edible>
</plant>
